repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0 
    hooks:
    -   id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
-   repo: https://github.com/psf/black.git
    rev: 25.1.0
    hooks:
    -   id: black